version: '3.7'

services:
  opensearch-node1:
    image: opensearchproject/opensearch:2.2.0
    container_name: opensearch-node1
    environment:
      - "logger.level=WARN"
      - "cluster.name=opensearch-cluster"
      - "node.name=opensearch-node1"
      - "discovery.seed_hosts=opensearch-node1,opensearch-node2"
      - "cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2"
      - "bootstrap.memory_lock=true"
      - "MAX_LOCKED_MEMORY=unlimited"
      - "OPENSEARCH_JAVA_OPTS=-server -Xms16g -Xmx16g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "path.repo=/opt/opensearch/backup"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
      - opensearch-backup1:/opt/opensearch/backup
      - ./certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem:ro
      - ./certs/admin.pem:/usr/share/opensearch/config/admin.pem:ro
      - ./certs/node2-key.pem:/usr/share/opensearch/config/node-key.pem:ro
      - ./certs/node2.pem:/usr/share/opensearch/config/node.pem:ro
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem:ro
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
      - ./security/audit.yml:/usr/share/opensearch/config/opensearch-security/audit.yml:ro
      - ./security/action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml:ro
      - ./security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml:ro
      - ./security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml:ro
      - ./security/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml:ro
      - ./security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml:ro
      - ./security/tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml:ro
    ports:
      - 0.0.0.0:9201:9200
      - 0.0.0.0:9601:9600
    networks:
      - default

  opensearch-node2:
    image: opensearchproject/opensearch:2.2.0
    container_name: opensearch-node2
    environment:
      - "logger.level=WARN"
      - "cluster.name=opensearch-cluster"
      - "node.name=opensearch-node2"
      - "discovery.seed_hosts=opensearch-node1,opensearch-node2"
      - "cluster.initial_cluster_manager_nodes=opensearch-node1,opensearch-node2"
      - "bootstrap.memory_lock=true"
      - "MAX_LOCKED_MEMORY=unlimited"
      - "OPENSEARCH_JAVA_OPTS=-server -Xms16g -Xmx16g -Xss256k -XX:-HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -Dlog4j.formatMsgNoLookups=true"
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=false"
      - "path.repo=/opt/opensearch/backup"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - opensearch-data2:/usr/share/opensearch/data
      - opensearch-backup2:/opt/opensearch/backup
      - ./certs/admin-key.pem:/usr/share/opensearch/config/admin-key.pem:ro
      - ./certs/admin.pem:/usr/share/opensearch/config/admin.pem:ro
      - ./certs/node2-key.pem:/usr/share/opensearch/config/node-key.pem:ro
      - ./certs/node2.pem:/usr/share/opensearch/config/node.pem:ro
      - ./certs/root-ca.pem:/usr/share/opensearch/config/root-ca.pem:ro
      - ./opensearch.yml:/usr/share/opensearch/config/opensearch.yml:ro
      - ./security/audit.yml:/usr/share/opensearch/config/opensearch-security/audit.yml:ro
      - ./security/action_groups.yml:/usr/share/opensearch/config/opensearch-security/action_groups.yml:ro
      - ./security/config.yml:/usr/share/opensearch/config/opensearch-security/config.yml:ro
      - ./security/internal_users.yml:/usr/share/opensearch/config/opensearch-security/internal_users.yml:ro
      - ./security/roles.yml:/usr/share/opensearch/config/opensearch-security/roles.yml:ro
      - ./security/roles_mapping.yml:/usr/share/opensearch/config/opensearch-security/roles_mapping.yml:ro
      - ./security/tenants.yml:/usr/share/opensearch/config/opensearch-security/tenants.yml:ro
    ports:
      - 0.0.0.0:9202:9200
      - 0.0.0.0:9602:9600
    networks:
      - default

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.2.0
    container_name: opensearch-dashboards
    ports:
      - 0.0.0.0:5601:5601
    environment:
       OPENSEARCH_HOSTS: '["https://opensearch-node1:9200","https://opensearch-node2:9200"]'
       DISABLE_SECURITY_DASHBOARDS_PLUGIN: "false"
    volumes:
      - ./certs/client-key.pem:/usr/share/opensearch-dashboards/config/client-key.pem:ro
      - ./certs/client.pem:/usr/share/opensearch-dashboards/config/client.pem:ro
      - ./certs/root-ca.pem:/usr/share/opensearch-dashboards/config/root-ca.pem:ro
      - ./opensearch_dashboards.yml:/usr/share/opensearch-dashboards/config/opensearch_dashboards.yml:ro
    networks:
      - default

  openldap:
    image: osixia/openldap
    container_name: openldap
    command: --copy-service
    ports:
      - 127.0.0.1:389:389
      - 127.0.0.1:636:636
    environment:
      - LDAP_ADMIN_PASSWORD=changethis
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_PASSWORD=changethistoo
    volumes:
      - ./directory.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/directory.ldif:ro
    networks:
      - default

  openldap-admin:
    image: osixia/phpldapadmin
    container_name: openldap-admin
    ports:
      - 127.0.0.1:6443:443
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    networks:
      - default

volumes:
  opensearch-data1:
  opensearch-data2:
  opensearch-backup1:
  opensearch-backup2:

networks:
  default:
    external: false