version: '3.7'

x-process-variables: &process-variables
  PUID : 1000
  PGID : 1000

x-auth-variables: &auth-variables
  NGINX_BASIC_AUTH : 'false'
  NGINX_LDAP_TLS_STUNNEL : 'false'
  NGINX_LDAP_TLS_STUNNEL_CHECK_HOST : ''
  NGINX_LDAP_TLS_STUNNEL_CHECK_IP : ''
  NGINX_LDAP_TLS_STUNNEL_VERIFY_LEVEL : 2
  NGINX_SSL : 'true'

################################################################################

services:

  netbox:
    image: ghcr.io/mmguero/netbox:latest
    build:
      context: .
      dockerfile: netbox/Dockerfile
    container_name: netbox
    hostname: netbox
    depends_on:
    - netbox-postgres
    - netbox-redis
    - netbox-redis-cache
    environment:
      << : *process-variables
    env_file: ./netbox/env/netbox.env
    volumes:
    - ./netbox/configuration:/etc/netbox/config:z,ro
    - ./netbox/media:/opt/netbox/netbox/media:z,rw
    - ./netbox/reports:/etc/netbox/reports:z,ro
    - ./netbox/scripts:/etc/netbox/scripts:z,ro
    - ./netbox/unit:/etc/unit:z,ro
    restart: "no"
    stdin_open: false
    tty: true
    healthcheck:
      test: ["CMD", "curl", "--silent", "http://localhost:8080/assets/api/" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    networks:
      - default

  netbox-postgres:
    image: ghcr.io/mmguero/postgres:14-alpine
    container_name: netbox-postgres
    hostname: netbox-postgres
    environment:
      << : *process-variables
    env_file: ./netbox/env/postgres.env
    volumes:
    - ./netbox/postgres:/var/lib/postgresql/data:rw
    restart: "no"
    stdin_open: false
    tty: true
    healthcheck:
      test: ["CMD", "pg_isready" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s
    networks:
      - default

  netbox-redis:
    image: ghcr.io/mmguero/redis:7-alpine
    container_name: netbox-redis
    hostname: netbox-redis
    command:
    - sh
    - -c
    - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD
    environment:
      << : *process-variables
    env_file: ./netbox/env/redis.env
    volumes:
    - ./netbox/redis:/data
    restart: "no"
    stdin_open: false
    tty: true
    healthcheck:
      test: ["CMD", "sh", "-c", "pidof redis-server || exit 1" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s
    networks:
      - default

  netbox-redis-cache:
    image: ghcr.io/mmguero/redis:7-alpine
    container_name: netbox-redis-cache
    hostname: netbox-redis-cache
    command:
    - sh
    - -c
    - redis-server --requirepass $$REDIS_PASSWORD
    environment:
      << : *process-variables
    env_file: ./netbox/env/redis-cache.env
    restart: "no"
    stdin_open: false
    tty: true
    healthcheck:
      test: ["CMD", "sh", "-c", "pidof redis-server || exit 1" ]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 45s
    networks:
      - default

  nginx-ldap:
    image: ghcr.io/mmguero/nginx-ldap:latest
    container_name: nginx-ldap
    hostname: nginx-ldap
    environment:
      << : *process-variables
      << : *auth-variables
    depends_on:
      - netbox
    ports:
      - "0.0.0.0:7443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_ldap.conf:/etc/nginx/nginx_ldap.conf:ro
      - ./nginx/htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/ca-trust:/etc/nginx/ca-trust:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--silent", "https://localhost:443"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s
    restart: "no"
    stdin_open: false
    tty: true
    networks:
      - default

networks:
  default:
    external: false
