services:

  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=false"
      - "--providers.file=true"
      - "--providers.file.directory=/etc/traefik/sites-enabled"
      - "--providers.file.watch=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      # - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      # - "--certificatesresolvers.myresolver.acme.caserver=https://ca.example.org:9000/acme/acme/directory"
      - "--certificatesresolvers.myresolver.acme.email=user@example.org"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
    volumes:
      - "./letsencrypt:/letsencrypt:rw"
      - "./certs:/etc/ssl/certs:ro"
      - "./rules:/etc/traefik/sites-enabled:ro"

  whoami:
    image: "traefik/whoami:latest"
    container_name: "whoami"
    expose:
      - 80
    networks:
      - default

networks:
  default:
    external:
      name: podman
