---
_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    http:
      anonymous_auth_enabled: false
    authc:
      internal_auth:
        order: 0
        description: "HTTP basic authentication using the internal user database"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: internal
      ldap_auth:
        order: 1
        description: "Authenticate using LDAP"
        http_enabled: true
        transport_enabled: true
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: ldap
          config:
            enable_ssl: true
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            pemtrustedcas_filepath: /usr/share/opensearch/config/root-ca.pem
            hosts:
            - glauth:636
            bind_dn: cn=binddn,dc=nein,dc=local
            password: "r3@d0n!y"
            userbase: ou=users,dc=nein,dc=local
            usersearch: (uid={0})
            username_attribute: uid
    authz:
      ldap_roles:
        description: "Authorize using LDAP"
        http_enabled: true
        transport_enabled: true
        authorization_backend:
          type: ldap
          config:
            enable_ssl: true
            enable_start_tls: false
            enable_ssl_client_auth: false
            verify_hostnames: false
            pemtrustedcas_filepath: /usr/share/opensearch/config/root-ca.pem
            hosts:
            - glauth:636
            bind_dn: cn=binddn,dc=nein,dc=local
            password: "r3@d0n!y" 
            userbase: ou=users,dc=nein,dc=local
            usersearch: (uid={0})
            username_attribute: uid
            rolebase: ou=groups,dc=nein,dc=local
            rolesearch: (memberUid={1})
            userroleattribute: null
            userrolename: none
            rolename: ou
            resolve_nested_roles: true
            skip_users:
              - admin
              - kibanaserver
