version: '3.7'

services:
  ca:
    image: smallstep/step-ca:latest
    ports:
      - "0.0.0.0:9000:9000"
    volumes:
      - ./step:/home/step:rw
      - ./secrets.txt:/home/step/secrets/password:ro
    restart: always

