version: '3'

services:

  booksonic:
    image: linuxserver/booksonic:latest
    container_name: booksonic
    hostname: booksonic
    expose:
      - 4040
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Denver
    volumes:
      - ./config:/config
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./othermedia:/othermedia
    restart: unless-stopped
    networks:
      - proxy

  proxy:
    image: nginx:alpine
    container_name: booksonic_proxy
    hostname: proxy
    links:
      - booksonic
    expose:
      - 80
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - proxy
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.booksonic.rule=Host(`booksonic.example.org`)"
      - "traefik.http.routers.booksonic.entrypoints=websecure"
      - "traefik.http.routers.booksonic.tls.certresolver=myresolver"

networks:
  proxy:
    external:
      name: traefik-proxy

