version: '3.7'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      # include any other IPs here as well (for VPN interfaces, etc.)
      - "127.0.0.1:53:53/tcp"
      - "127.0.0.1:53:53/udp"
      - "127.0.0.1:8000:80/tcp"
      - "127.0.0.1:8443:443/tcp"
    environment:
      TZ: 'America/Denver'
      WEBPASSWORD: 'password'
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
      # run `touch ./var-log/pihole.log` first unless you like errors
      - './var-log/pihole.log:/var/log/pihole.log'
    dns:
      - 127.0.0.1
      - 1.1.1.1
    restart: unless-stopped
