services:

  calibre:
    image: lscr.io/linuxserver/calibre-web:latest
    # platform: linux/arm64/v8
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calibre
    expose:
      - 8083
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Denver
      - DOCKER_MODS=linuxserver/mods:universal-calibre
    volumes:
      - ./config:/config:rw
      - ./data:/books:rw
      # - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./scripts:/custom-cont-init.d:ro
    restart: unless-stopped
    # ports:
    #   - 127.0.0.1:8083:8083
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`calibre.example.org`)"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.tls.certresolver=myresolver"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"

networks:
  proxy:
    name: traefik-proxy
    external: true

