version: '3'

services:

  calibre:
    image: ghcr.io/mmguero/calibre-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: calibre
    expose:
      - 8083
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Denver
    volumes:
      - ./config:/config:rw
      - ./data:/books:rw
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre.rule=Host(`calibre.example.org`)"
      - "traefik.http.routers.calibre.entrypoints=websecure"
      - "traefik.http.routers.calibre.tls.certresolver=myresolver"
      - "traefik.http.services.calibre.loadbalancer.server.port=8083"

networks:
  proxy:
    external:
      name: traefik-proxy


