version: '3.7'

services:
  gogs:
    container_name: gogs
    image: gogs/gogs:latest
    volumes:
      - ./data:/data
    expose:
      - 3000
      - 10022
    ports:
      - "0.0.0.0:10022:22/tcp"
      - "0.0.0.0:3000:3000/tcp"
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gogs.rule=Host(`gogs.example.org`)"
      - "traefik.http.routers.gogs.entrypoints=websecure"
      - "traefik.http.routers.gogs.tls.certresolver=myresolver"
      - "traefik.http.services.gogs.loadbalancer.server.port=3000"
    restart: unless-stopped

networks:
  proxy:
    external:
      name: traefik-proxy