version: '3.9'

services:
  roop:
    image: oci.guero.top/roop:latest
    build:
      context: .
      dockerfile: Dockerfile
    restart: no
    env_file:
      - .env
    command: nvidia-smi
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [compute, utility, video]
