version: "2.1"

services:

  mastodon:
    image: oci.guero.org/mastodon:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mastodon
    env_file: ./env.production
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - LOCAL_DOMAIN=mastodon.example.com
      # - ALTERNATE_DOMAINS=127.0.0.1,localhost
    volumes:
      - ./config:/config
    ports:
      - "127.0.0.1:45580:80"
      - "127.0.0.1:45543:443"
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'wget -q --spider --proxy=off localhost:3000/health || exit 1']
    depends_on:
      - redis
      - postgres

  redis:
    image: docker.io/bitnami/redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  postgres:
    hostname: db
    container_name: postgres
    image: docker.io/library/postgres:10.5
    env_file: ./env.postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    networks:
      - default
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
    restart: unless-stopped

networks:
  default:
    external: false
