version: "2.1"

services:

  mastodon:
    image: ghcr.io/mmguero/mastodon:latest
    container_name: mastodon
    env_file: ./env.production
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/Denver
      - LOCAL_DOMAIN=mastodon.example.com
    volumes:
      - ./config:/config
    ports:
      - "127.0.0.1:45580:80"
      - "127.0.0.1:45543:443"
    networks:
      - default
    restart: unless-stopped
    depends_on:
      - redis
      - postgres

  redis:
    image: docker.io/bitnami/redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - default
    restart: unless-stopped

  postgres:
    hostname: db
    container_name: postgres
    image: docker.io/library/postgres:10.5
    env_file: ./env.postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - default
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: unless-stopped

networks:
  default:
    external: false
