services:
  owntracks:
    image: owntracks/recorder:latest
    container_name: owntracks
    hostname: owntracks
    restart: "no"
    environment:
      OTR_PORT : '0'
    networks:
      - default
    # ports:
    #   - "127.0.0.1:8083:8083"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./config:/config:rw
      - ./store:/store:rw

networks:
  default:
    external: false
