[http.routers]

   [http.routers.web]
      rule = "Host(`web.example.org`)"
      entrypoints = ["websecure"]
      service = "web"
   [http.routers.web.tls]
      certResolver = "myresolver"

[http.services]

   [http.services.web.loadBalancer]
      [[http.services.web.loadBalancer.servers]]
         url = "http://host.containers.internal:9443"
