[http.routers]

   [http.routers.whoami]
      rule = "Host(`whoami.example.org`)"
      entrypoints = ["websecure"]
      service = "whoami"
   [http.routers.whoami.tls]
      certResolver = "myresolver"

[http.services]

   [http.services.whoami.loadBalancer]
      [[http.services.whoami.loadBalancer.servers]]
         url = "http://whoami:80"
