version: '3'

services:

  booksonic:
    image: linuxserver/booksonic:latest
    container_name: booksonic
    hostname: booksonic
    expose:
      - 4040
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Denver
    volumes:
      - ./config:/config
      - ./audiobooks:/audiobooks
      - ./podcasts:/podcasts
      - ./othermedia:/othermedia
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    container_name: booksonic_proxy
    hostname: proxy
    links:
      - booksonic
    expose:
      - 443
    ports:
      - 0.0.0.0:4043:443
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy/certs:/etc/nginx/certs:ro

