version: '3.8'

services:
  webapp:
    restart: unless-stopped
    image: nodeapp
    build: .
    # ports:
    #   - 127.0.0.1:3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - default

  proxy:
    restart: unless-stopped
    image: nginx:alpine
    ports:
      - 127.0.0.1:8000:80
    depends_on:
      - webapp
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - default

networks:
  default:
    external: false
