services:

  uptime-kuma:
    image: louislam/uptime-kuma:latest
    container_name: uptime-kuma
    expose:
      - 3001 
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/Denver
      - NODE_ENV=production
      - NODE_EXTRA_CA_CERTS=/extra_ca.crt
    volumes:
      - ./data:/app/data
      - ./extra_ca.crt:/extra_ca.crt:ro
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.uptime.rule=Host(`uptime.example.org`)"
      - "traefik.http.routers.uptime.entrypoints=websecure"
      - "traefik.http.routers.uptime.tls.certresolver=myresolver"
      - "traefik.http.services.uptime.loadbalancer.server.port=3001"

networks:
  proxy:
    external:
      name: traefik-proxy
