version: '3'

x-process-variables: &process-variables
  # If you're using podman (which does the UID/GUID mapping for you)
  # change PUID/PGID to 0, uncomment PUSER_PRIV_DROP : 'false' and
  # set '--user=mysql' to '--user=root' in the ctfd command section.
  PUID : 1000
  PGID : 1000
  # PUSER_PRIV_DROP : 'false'

x-auth-variables: &auth-variables
  # authentication method: encrypted HTTP basic authentication ('true') vs LDAP ('false')
  # vs unauthenticated ('no_authentication')
  NGINX_BASIC_AUTH : 'no_authentication'
  # NGINX LDAP (NGINX_BASIC_AUTH=false) can support LDAP, LDAPS, or LDAP+StartTLS.
  #   For StartTLS, set NGINX_LDAP_TLS_STUNNEL=true to issue the StartTLS command
  #   and use stunnel to tunnel the connection.
  NGINX_LDAP_TLS_STUNNEL : 'false'
  # stunnel will require and verify certificates for StartTLS when one or more
  # trusted CA certificate files are placed in the ./nginx/ca-trust directory.
  # For additional security, hostname or IP address checking of the associated
  # CA certificate(s) can be enabled by providing these values.
  NGINX_LDAP_TLS_STUNNEL_CHECK_HOST : ''
  NGINX_LDAP_TLS_STUNNEL_CHECK_IP : ''
  NGINX_LDAP_TLS_STUNNEL_VERIFY_LEVEL : 2
  # Whether or not nginx should use HTTPS. This is almost CERTAINLY what you want.
  # The only case you may want to set this to false is if you're using another
  # reverse proxy in front of NGINX. Even if set to 'false', NGINX will still
  # listen on port 443 (it just won't be encrypted). If you change this, you'll
  # probably want to change "0.0.0.0:443:443" to something like
  # "127.0.0.1:80:443" in the ports section for the nginx-ldap service and
  # change "https://" to "http://" in its healthcheck.
  NGINX_SSL : 'true'

services:
  nginx-ldap:
    image: oci.guero.top/nginx-ldap:latest
    container_name: nginx-ldap
    hostname: nginx-ldap
    restart: unless-stopped
    environment:
      << : *process-variables
      << : *auth-variables
    depends_on:
      - ctfd
    networks:
      - default
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/nginx_ldap.conf:/etc/nginx/nginx_ldap.conf:ro
      - ./nginx/htpasswd:/etc/nginx/.htpasswd:ro
      - ./nginx/ca-trust:/etc/nginx/ca-trust:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--silent", "https://localhost:443"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s

  ctfd:
    image: oci.guero.top/ctfd:latest
    container_name: ctfd
    hostname: ctfd
    restart: unless-stopped
    environment:
      << : *process-variables
      UPLOAD_FOLDER : '/var/uploads'
      DATABASE_URL : 'mysql+pymysql://ctfd:Correct_Horse_Battery_Staple@db/ctfd'
      REDIS_URL : 'redis://cache:6379'
      WORKERS : 5
      LOG_FOLDER : '/var/log/CTFd'
      ACCESS_LOG : '-'
      ERROR_LOG : '-'
      REVERSE_PROXY : 'true'
      SECRET_KEY : 'Mistake_After_Childhood_Roar'
    volumes:
      - ./data/CTFd/logs:/var/log/CTFd:rw
      - ./data/CTFd/uploads:/var/uploads:rw
    depends_on:
      - db
    networks:
      - default

  db:
    image: oci.guero.top/mariadb:latest
    container_name: db
    hostname: db
    restart: unless-stopped
    environment:
      << : *process-variables
      MYSQL_ROOT_PASSWORD : 'ctfd'
      MYSQL_USER : 'ctfd'
      MYSQL_PASSWORD : 'Correct_Horse_Battery_Staple'
      MYSQL_DATABASE : 'ctfd'
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - default
    command: [mysqld, --user=mysql, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: oci.guero.top/redis:latest
    container_name: cache
    hostname: cache
    restart: unless-stopped
    networks:
      - default
    environment:
      << : *process-variables
    command:
      - sh
      - -c
      - redis-server
    volumes:
      - ./data/redis:/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pidof redis-server || exit 1" ]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 45s

networks:
    default:
      external: false
