version: '3'

x-process-variables: &process-variables
  # If you're using podman (which does the UID/GUID mapping for you)
  # change PUID/PGID to 0, uncomment PUSER_PRIV_DROP : 'false' and
  # set '--user=mysql' to '--user=root' in the ctfd command section.
  PUID : 1000
  PGID : 1000
  # PUSER_PRIV_DROP : 'false'

x-auth-variables: &auth-variables
  # Authentication is handled by CTFd, not nginx
  NGINX_BASIC_AUTH : 'no_authentication'
  # TLS is enabled
  NGINX_SSL : 'true'

services:
  nginx:
    image: oci.guero.top/nginx-ldap:latest
    container_name: nginx
    hostname: nginx
    restart: unless-stopped
    environment:
      << : *process-variables
      << : *auth-variables
    depends_on:
      - ctfd
    networks:
      - default
    ports:
      - "0.0.0.0:443:443"
      - "0.0.0.0:80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ca-trust:/etc/nginx/ca-trust:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/certs/dhparam.pem:/etc/nginx/dhparam/dhparam.pem:ro
    healthcheck:
      test: ["CMD", "curl", "--insecure", "--silent", "https://localhost:443"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 120s

  ctfd:
    image: oci.guero.top/ctfd:latest
    container_name: ctfd
    hostname: ctfd
    restart: unless-stopped
    environment:
      << : *process-variables
      UPLOAD_FOLDER : '/var/uploads'
      DATABASE_URL : 'mysql+pymysql://ctfd:Correct_Horse_Battery_Staple@db/ctfd'
      REDIS_URL : 'redis://cache:6379'
      WORKERS : 5
      LOG_FOLDER : '/var/log/CTFd'
      ACCESS_LOG : '-'
      ERROR_LOG : '-'
      REVERSE_PROXY : 'true'
      SECRET_KEY : 'Mistake_After_Childhood_Roar'
    volumes:
      - ./data/CTFd/logs:/var/log/CTFd:rw
      - ./data/CTFd/uploads:/var/uploads:rw
    depends_on:
      - db
    networks:
      - default
    # ports:
    #   - "127.0.0.1:8000:8000"

  db:
    image: oci.guero.top/mariadb:latest
    container_name: db
    hostname: db
    restart: unless-stopped
    environment:
      << : *process-variables
      MYSQL_ROOT_PASSWORD : 'ctfd'
      MYSQL_USER : 'ctfd'
      MYSQL_PASSWORD : 'Correct_Horse_Battery_Staple'
      MYSQL_DATABASE : 'ctfd'
    volumes:
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - default
    command: [mysqld, --user=mysql, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

  cache:
    image: oci.guero.top/redis:latest
    container_name: cache
    hostname: cache
    restart: unless-stopped
    networks:
      - default
    environment:
      << : *process-variables
    command:
      - sh
      - -c
      - redis-server
    volumes:
      - ./data/redis:/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pidof redis-server || exit 1" ]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 45s

networks:
    default:
      external: false
