services:
  libreoffice:
    image: lscr.io/linuxserver/libreoffice:latest
    container_name: libreoffice
    hostname: libreoffice
    restart: unless-stopped
    environment:
      PUID : 1000
      PGID : 1000
      TZ : "America/Denver"
      DISABLE_IPV6 : true
    ports:
      - "127.0.0.1:3000:3000"
      - "127.0.0.1:3001:3001"
    volumes:
      - ./config:/config:z
      # - /home/user/Documents:/files/Documents:z
      # - /home/user/.fonts:/usr/share/fonts/user:z
      - /usr/share/fonts:/usr/share/fonts/host:z
