services:
  musescore:
    image: oci.guero.org/musescore-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musescore
    hostname: musescore
    restart: "no"
    environment:
      USER_ID : 1000
      GROUP_ID : 1000
      WEB_AUDIO : 1
      WEB_AUTHENTICATION : 0
      SECURE_CONNECTION : 0
      VNC_LISTENING_PORT : -1
      WEB_LISTENING_PORT : 5800
    networks:
      - default
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./files
        target: /musescore-files

  musescore-files:
    image: docker.io/pldubouilh/gossa:latest
    container_name: musescore-files
    hostname: musescore-files
    restart: "no"
    user: "1000:1000"
    # userns_mode: "keep-id"
    # x-podman:
    #   in_pod: false
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    read_only: true
    environment:
      # READONLY : true
      PREFIX : /files/
      UID : 1000
      GID : 1000
    networks:
      - default
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./files
        target: /shared

  nginx:
    image: oci.guero.org/nginx-ldap:latest
    container_name: nginx
    hostname: nginx
    restart: "no"
    environment:
      PUID : 1000
      PGID : 1000
      NGINX_BASIC_AUTH : 'true'
      NGINX_SSL : 'false'
    depends_on:
      - musescore
      - musescore-files
    networks:
      - default
    ports:
      - "127.0.0.1:5800:443"
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./nginx/nginx.conf
        target: /etc/nginx/nginx.conf
        read_only: true
      - type: bind
        bind:
          create_host_path: false
        source: ./nginx/nginx_ldap.conf
        target: /etc/nginx/nginx_ldap.conf
        read_only: true
      - type: bind
        bind:
          create_host_path: false
        source: ./nginx/htpasswd
        target: /etc/nginx/htpasswd
        read_only: true
      - type: bind
        bind:
          create_host_path: false
        source: ./nginx/ca-trust
        target: /etc/nginx/ca-trust
        read_only: true
      - type: bind
        bind:
          create_host_path: false
        source: ./nginx/certs
        target: /etc/nginx/certs
        read_only: true
      - type: bind
        bind:
          create_host_path: false
        source: ./nginx/certs/dhparam.pem
        target: /etc/nginx/dhparam/dhparam.pem
        read_only: true

networks:
  default:
    external: false
