services:
  musescore:
    image: oci.guero.org/musescore-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musescore
    hostname: musescore
    restart: unless-stopped
    environment:
      USER_ID : 1000
      GROUP_ID : 1000
      WEB_AUDIO : 1
      WEB_AUTHENTICATION : 0
      SECURE_CONNECTION : 0
      VNC_LISTENING_PORT : -1
      WEB_LISTENING_PORT : 5800
    networks:
      - default
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./files
        target: /musescore-files

  musescore-files:
    image: oci.guero.org/gossa:latest
    restart: unless-stopped
    hostname: musescore-files
    networks:
      - default
    environment:
      - PUID=1000
      - PGID=1000
      - HOST=0.0.0.0
      - PORT=8001
      - PREFIX=/
      - FOLLOW_SYMLINKS=false
      - SKIP_HIDDEN_FILES=true
      - DATADIR=/shared
      - READONLY=false
      - VERBOSE=false
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./files
        target: /shared

networks:
  default:
    external: false
