services:
  musescore:
    image: oci.guero.org/musescore-web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: musescore
    hostname: musescore
    restart: "no"
    environment:
      USER_ID : 1000
      GROUP_ID : 1000
      WEB_AUDIO : 1
      WEB_AUTHENTICATION : 0
      SECURE_CONNECTION : 0
      VNC_LISTENING_PORT : -1
      WEB_LISTENING_PORT : 5800
    networks:
      - default
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./files
        target: /musescore-files

  musescore-files:
    image: docker.io/pldubouilh/gossa:latest
    container_name: musescore-files
    hostname: musescore-files
    restart: "no"
    user: "1000:1000"
    # userns_mode: "keep-id"
    # x-podman:
    #   in_pod: false
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
    read_only: true
    environment:
      # READONLY : true
      PREFIX : /files/
      UID : 1000
      GID : 1000
    networks:
      - default
    volumes:
      - type: bind
        bind:
          create_host_path: false
        source: ./files
        target: /shared

networks:
  default:
    external: false
