---
name: debian-stable-slim-build-push-ghcr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'debian/**'
      - '.github/workflows/debian-stable-slim-build-push-ghcr.yml'
  pull_request:
    paths:
      - 'debian/**'
      - '.github/workflows/debian-stable-slim-build-push-ghcr.yml'
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

jobs:
  docker:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    steps:
      -
        name: Cancel previous run in progress
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: |
            image=moby/buildkit:master
      -
        name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./debian
          file: ./debian/Dockerfile
          build-args: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/debian:latest
          platforms: linux/amd64,linux/arm64,linux/arm/v7
