---
name: forgejo-root-build-push-ghcr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'forgejo/**'
      - '.github/workflows/forgejo-root-build-push-ghcr.yml'
  pull_request:
    paths:
      - 'forgejo/**'
      - '.github/workflows/forgejo-root-build-push-ghcr.yml'
  workflow_dispatch:
  repository_dispatch:
  schedule:
    - cron: '0 12 15 * *'

jobs:
  build-image:
    name: Call Docker Build
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: ./forgejo
      file: ./forgejo/Dockerfile
      cancel-previous-runs: true
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/forgejo
      tag-rules: |
        type=raw,value=root,enable={{is_default_branch}}
        type=raw,value=root-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
      platforms: linux/amd64
