name: mattermost-build-push-ghcr

on:
  push:
    branches:
      - 'master'
    paths:
      - 'mattermost/**'
  workflow_dispatch:
  repository_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      packages: write
      contents: read
    steps:
      -
        name: Cancel previous run in progress
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          ignore_sha: true
          all_but_latest: true
          access_token: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push mattermost
        uses: docker/build-push-action@v2
        with:
          context: ./mattermost
          file: ./mattermost/docker/mattermost.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/mattermost-server:latest
      -
        name: Build and push postgres
        uses: docker/build-push-action@v2
        with:
          context: ./mattermost
          file: ./mattermost/docker/postgres.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/postgres:13-alpine
