name: mattermost-build-push

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push mattermost
        uses: docker/build-push-action@v2
        with:
          context: ./services/mattermost
          file: ./services/mattermost/docker/mattermost.Dockerfile
          push: true
          tags: mmguero/mattermost-server:latest
      -
        name: Build and push postgres
        uses: docker/build-push-action@v2
        with:
          context: ./services/mattermost
          file: ./services/mattermost/docker/postgres.Dockerfile
          push: true
          tags: mmguero/postgres:13-alpine
