---
name: roop-build-push-ghcr

on:
  workflow_dispatch:
  # repository_dispatch:
  # push:
  #   branches:
  #     - 'master'
  #   paths:
  #     - 'roop/**'
  #     - '.github/workflows/roop-build-push-ghcr.yml'
  # pull_request:
  #   paths:
  #     - 'roop/**'
  #     - '.github/workflows/roop-build-push-ghcr.yml'
  # schedule:
  #   - cron: '0 12 15 * *'

jobs:
  build-image:
    name: Call Docker Build
    uses: mmguero-dev/docker-build-workflow/.github/workflows/reusable-docker-build.yaml@main
    permissions:
      contents: read
      actions: write
      packages: write
      pull-requests: write
    with:
      context: ./roop
      file: ./roop/Dockerfile
      cancel-previous-runs: true
      dockerhub-enable: false
      ghcr-enable: true
      image-names: |
        ghcr.io/${{ github.repository_owner }}/roop
      tag-rules: |
        type=raw,value=latest,enable={{is_default_branch}}
        type=raw,value=stable-{{date 'YYYYMMDDHHmmss'}},enable={{is_default_branch}}
        type=ref,event=pr
        type=ref,event=branch
        type=raw,value=gha-${{ github.run_id }}
      platforms: linux/amd64
